routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/invite', 'UsersController@inviteUsers')->name('users.invite');
Route::get('users/removeuser/{user}', 'UsersController@remove')->name('users.remove');
Route::get('users/makeleader/{user}', 'UsersController@makeLeader')->name('users.makeLeader');

Route::resource('/teams', 'TeamsController');
Route::resource('/tasks', 'TasksController');

// Route::middleware(['auth', 'admin'])->group(function(){
//     Route::resource('/teams', 'TeamsController');
// });

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;

class Task extends Model
{
    protected $fillable = [
        'title',
        'description',
        'due_date',
        'priority',
        'status',
        'user_id',
        'team_id',
    ];
    public function getUser($user_id) {
        return DB::table('users')->where('id', $user_id)->get()->first();
    }
    public static function autoAssign($team_id) {
        $totalPoints = 0;
        $allUsersTotalPoint = [];
        $users = User::all()->where('team_id', '=', $team_id);
        foreach($users as $user) {
            $points = Points::all()->where('user_id', '=', $user->id);
            // dd($points->first() == null);
            if($points->first() != null){
                foreach($points as $point) {
                    $totalPoints += $point->point;
                }
                array_push($allUsersTotalPoint, [['user_id' => $user->id], ['point' => $totalPoints]]);
                // dd($allUsersTotalPoint);
                $totalPoints = 0;
            }
        }
        // dd($allUsersTotalPoint);
        $bestUser = collect($allUsersTotalPoint)->sortBy($totalPoints);
        // dd($bestUser->first()[0]['user_id']);
        return $bestUser->first()[0]['user_id'];
    }

    /**
     * Relationship Methods
     */
    public function owner(){
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role', 'team_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public static function bestEmpolyeeOfTheMonth() {
        $totalPoints = 0;
        $allUsersTotalPoint = [];
        $users = User::all();
        foreach($users as $user) {
            $points = Points::all()->where('user_id', '=', $user->id);
            // dd($points->first() == null);
            if($points->first() != null){
                foreach($points as $point) {
                    $totalPoints += $point->point;
                }
                array_push($allUsersTotalPoint, [['user' => $user], ['point' => $totalPoints]]);
                // dd($allUsersTotalPoint);
                $totalPoints = 0;
            }
        }
        // dd($allUsersTotalPoint);
        $empOfTheMonth = collect($allUsersTotalPoint)->sortBy($totalPoints);
        // dd($empOfTheMonth->first()[0]['user_id']);
        // $bestEmpOfTheMonth = new BestEmpOfTheMonth;
        // $bestEmpOfTheMonth->user_id = $empOfTheMonth->first()[0]['user_id'];
        // $bestEmpOfTheMonth->date = Carbon::now();
        // $bestEmpOfTheMonth->save();
        // dd($empOfTheMonth->first()[0]['user']->id);
        $bestEmpOfTheMonth = BestEmpOfTheMonth::create([
            'user_id' => $empOfTheMonth->first()[0]['user']->id,
            'date' => Carbon::now(),
        ]);
        return $empOfTheMonth->first()[0]['user']->name;
    }


    /**
     * ACCESSORS
     */

    public function getAvatarAttribute() {
        $size = 36;
        $font_size = "0.4rem";
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}&font-size={$font_size}";
    }

    public function isAdmin(){
        return $this->role === 'admin';
    }

    public function isLeader(){
        return $this->role === 'leader';
    }

    public function isMember(){
        return $this->role === 'member';
    }


    /**
     * Relationship Methods
     *
     */
    public function tasks(){
        return $this->hasMany(Task::class);
    }
    public function teams(){
        return $this->belongsTo(Team::class);
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Task\CreateTaskRequest;
use App\Http\Requests\Task\UpdateTaskRequest;
use App\Points;
use App\Task;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::all();
        return view('tasks.index', compact([
            'tasks'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $team_id = auth()->user()->team_id;
        $users = DB::table('users')->where('team_id', '=', $team_id)->get();
        return view('tasks.create', compact([
            'users'
        ]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTaskRequest $request)
    {
        // dd($request->team_id);
        $status = "inprogress";
        if($request->user == "-2"){
            $user_id = Task::autoAssign($request->team_id);
        }elseif($request->user == "-1"){
            $user_id = null;
            $status = "open";
        }else{
            $user_id = $request->user;
        }
        $task = Task::create([
            'user_id' => $user_id,
            'team_id' => $request->team_id,
            'title' => $request->title,
            'description' => $request->description,
            'due_date' => $request->due_date,
            'priority' => $request->priority,
            'status' => $status,
        ]);

        session()->flash('success', "Task has been added successfully!");
        return redirect(route('tasks.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        return view('tasks.show', compact([
            'task',
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        $team_id = auth()->user()->team_id;
        $users = DB::table('users')->where('team_id', '=', $team_id)->get();
        return view('tasks.edit', compact([
            'task',
            'users'
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTaskRequest $request, Task $task)
    {
        $points = DB::table('points')->where([
            ['user_id', '=', $task->user_id],
            ['task_id', '=', $task->id]
        ])->get()->first();
        if($points == null){
            $oldPoint = 0;
        }else{
            $oldPoint = $points->point;
        }
        if($request->status == "underreview"){
            $point = $oldPoint + $task->priority;
        }elseif($request->status == "quitted"){
            $point = $oldPoint - 2;
        }elseif($request->status == "rejected"){
            $point = $oldPoint - 2;
        }elseif($request->status == "approved"){
            $point = $oldPoint + 1;
        }
        if($points == null){
            $points = new Points;
            $points->user_id = $task->user_id;
            $points->task_id = $task->id;
            $points->point = $point;
            $points->status = $request->status;
            $points->save();
        }else{
            DB::table('points')->where([
                ['user_id', '=', $task->user_id],
                ['task_id', '=', $task->id]
            ])->update([
                'point' => $point,
                'status' => $request->status
            ]);
        }
        $task->update([
            'status'=>$request->status
        ]);
        session()->flash('success', "Task has been updated successfully!");
        return redirect(route('tasks.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        //
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('tasks.store') }}" method="POST">
                        @csrf
                        @if (Gate::allows('isLeader'))
                            <input type="text" name="team_id" id="team_id" value={{ auth()->user()->team_id }}>
                            <div class="form-group">
                                <h4>Create Tasks</h4>
                                <label for="title" class="mt-2">Title</label>
                                <input type="text"
                                       value="{{ old('title') }}"
                                       class="form-control @error('title') is-invalid @enderror"
                                       id="title" name="title"
                                       placeholder="Task Title">
                                @error('title')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="description">Description</label>
                                <input id="description" type="hidden" name="description" value="{{ old('description') }}">
                                <trix-editor input="description"></trix-editor>
                                @error('description')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="user" class="mt-2">Assign To</label>
                                <select name="user" id="user" class="form-control">
                                    <option value="-2" >Automatic</option>
                                    <option value="-1" >Unassigned</option>
                                    @foreach ($users as $user)
                                        <option value="{{ $user->id }}" >{{ $user->name }}</option>
                                    @endforeach
                                </select>
                                @error('user')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="due_date">Due Date</label>
                                <input type="date"
                                       value="{{ old('due_date') }}"
                                       class="form-control"
                                       name="due_date" id="due_date"
                                       min={{ Carbon\Carbon::now() }}>
                            </div>

                            <div class="form-group">
                                <label for="priority" class="mt-2">Priority</label>
                                <select name="priority" id="priority" class="form-control">
                                    <option value="2">Low</option>
                                    <option value="5">Medium</option>
                                    <option value="8">High</option>
                                </select>
                                @error('priority')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <button class="btn btn-success mt-4" type="submit">Add Task</button>
                        @endif
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection
@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('tasks.update', $task) }}" method="POST">
                        @csrf
                        @method('PUT')
                        @if (Gate::allows('isLeader'))
                            <input type="hidden" name="team_id" id="team_id" value={{ auth()->user()->team_id }}>
                            <div class="form-group">
                                <h4>Edit Tasks</h4>
                                <label for="title" class="mt-2">Title</label>
                                <input type="text"
                                       value="{{ old('title', $task->title) }}"
                                       class="form-control @error('title') is-invalid @enderror"
                                       id="title" name="title"
                                       placeholder="Task Title">
                                @error('title')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="description">Description</label>
                                <input id="description" type="hidden" name="description" value="{{ old('description', $task->description) }}">
                                <trix-editor input="description"></trix-editor>
                                @error('description')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="user" class="mt-2">Assign To</label>
                                <select name="user" id="user" class="form-control">
                                    <option value="-2">Automatic</option>
                                    <option value="-1">Unassigned</option>
                                    @foreach ($users as $user)
                                        <option value="{{ $user->id }}" {{ $task->user_id == $user->id ? 'selected' : '' }}>{{ $user->name }}</option>
                                    @endforeach
                                </select>
                                @error('user')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="due_date">Due Date</label>
                                <input type="text"
                                       value="{{ old('due_date', $task->due_date) }}"
                                       class="form-control"
                                       name="due_date" id="due_date"
                                       min={{ Carbon\Carbon::now() }}>
                            </div>

                            <div class="form-group">
                                <label for="priority" class="mt-2">Priority</label>
                                <select name="priority" id="priority" class="form-control">
                                    <option value="2" {{ $task->priority == "2" ? 'selected' : '' }}>Low</option>
                                    <option value="5" {{ $task->priority == "5" ? 'selected' : '' }}>Medium</option>
                                    <option value="8" {{ $task->priority == "8" ? 'selected' : '' }}>High</option>
                                </select>
                                @error('priority')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <button class="btn btn-success mt-4" type="submit">Update Task</button>
                        @endif
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection
@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    Task Details
                    <a class="back float-right" href="{{ route('tasks.index') }}"><i class="fa fa-chevron-circle-left" aria-hidden="true"></i> Back</a>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9">
                            <h4 class="mb-4">{{ $task->title }}</h4>
                            <small class="font-weight-bold">Description</small>
                            <p class="mt-2">{!! $task->description !!}</p>
                            @if (Gate::allows('isLeader'))
                                <form action="{{ route('tasks.edit', $task->id) }}" method="GET">
                                    @csrf
                                    <button class="btn btn-dark" type="submit">Edit Task</button>
                                </form>
                            @endif
                        </div>

                        <div class="col-md-3">
                            <div>
                                <small class="font-weight-bold d-block">Status</small>
                                @if ($task->status == "open")
                                <p class="d-inline-block mt-2 pl-2 pr-2 bg-secondary text-white">Open</p>
                                @elseif ($task->status == "inprogress")
                                    <p class="d-inline-block mt-2 pl-2 pr-2 bg-primary text-white">In Progress</p>
                                    @if (Gate::allows('isMember'))
                                        <div class="d-flex">
                                            <form action="{{ route('tasks.update', $task->id) }}" method="POST">
                                                @csrf
                                                @method('PUT')
                                                <input type="hidden" id="status" name="status" value="quitted">
                                                <button class="btn btn-danger btn-sm mr-2" type="submit">Quit Task</button>
                                            </form>
                                            <form action="{{ route('tasks.update', $task->id) }}" method="POST">
                                                @csrf
                                                @method('PUT')
                                                <input type="hidden" id="status" name="status" value="underreview">
                                                <button class="btn btn-success btn-sm" type="submit">Submit Task</button>
                                            </form>
                                        </div>
                                    @endif
                                @elseif($task->status == "quitted")
                                    <p class="d-inline-block mt-2 pl-2 pr-2 bg-danger text-white">Quitted</p>
                                    @if (Gate::allows('isLeader'))
                                        <div class="d-flex">
                                            <form action="{{ route('tasks.edit', $task->id) }}" method="GET">
                                                @csrf

                                                <input type="hidden" id="status" name="status" value="inprogress">
                                                <button class="btn btn-secondary btn-sm mr-2" type="submit">Reassign</button>
                                            </form>
                                        </div>
                                    @endif
                                @elseif($task->status == "underreview")
                                    <p class="d-inline-block mt-2 pl-2 pr-2 bg-warning">Under Review</p>
                                    @if (Gate::allows('isLeader'))
                                        <div class="d-flex">
                                            <form action="{{ route('tasks.update', $task->id) }}" method="POST">
                                                @csrf
                                                @method('PUT')
                                                <input type="hidden" id="status" name="status" value="rejected">
                                                <button class="btn btn-danger btn-sm mr-2" type="submit">Reject</button>
                                            </form>
                                            <form action="{{ route('tasks.update', $task->id) }}" method="POST">
                                                @csrf
                                                @method('PUT')
                                                <input type="hidden" id="status" name="status" value="approved">
                                                <button class="btn btn-success btn-sm" type="submit">Approve</button>
                                            </form>
                                        </div>
                                    @endif
                                @elseif($task->status == "rejected")
                                    <p class="d-inline-block mt-2 pl-2 pr-2 bg-danger text-white">Rejected</p>
                                @elseif($task->status == "approved")
                                    <p class="d-inline-block mt-2 pl-2 pr-2 bg-success text-white">Approved</p>
                                @endif
                            </div>

                            <div class="mt-2">
                                <small class="font-weight-bold">Assignee</small>
                                @if ($task->owner)
                                    <div class="mt-2">
                                        <img src="{{ $task->owner->avatar }}" alt=""> {{ $task->owner->name }}
                                    </div>
                                @else
                                    <p class="text-muted mt-2">Not Yet Assigned</p>
                                @endif
                            </div>
                            <div class="mt-4">
                                <small class="font-weight-bold">Due Date</small>
                                <p class="mt-2">{{ date('d/m/Y', strtotime($task->due_date)) }}</p>
                            </div>
                            <div class="mt-4">
                                <small class="font-weight-bold">Priority</small>
                                <p class="mt-2">
                                    @if ($task->priority == 2)
                                        <i class="fa fa-long-arrow-down low" aria-hidden="true"></i> Low
                                    @elseif ($task->priority == 5)
                                        <i class="fa fa-long-arrow-up medium" aria-hidden="true"></i> Medium
                                    @elseif ($task->priority == 8)
                                        <i class="fa fa-long-arrow-up high" aria-hidden="true"></i> High
                                    @endif
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css">
@endsection
@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
@endsection